### ISSUE TITLE
revisione project plan

### ISSUE THREAD

**Issue by alexxiuccia** [alexxiuccia/TrackMe#3]
salve @garganti 
le sottoponiamo il project plan che può trovare nella cartella ["documentazione/ProjectPlan.md"](https://github.com/alexxiuccia/TrackMe/blob/main/documentazione/ProjectPlan.md),
prevediamo la consegna per l'appello di febbraio

in attesa di un suo gentile riscontro

cordiali saluti

**Comment by garganti** [comment]
approvato . buon lavoro
